#!/bin/bash

# this script is maintained here: https://github.com/openSUSE/obs-service-format_spec_file
# SPDX-License-Identifier: GPL-2.0-or-later

set -e -o pipefail

export LC_ALL=C
curl -fsSL 'https://docs.google.com/spreadsheets/d/14AdaJ6cmU0kvQ4ulq9pWpjdZL5tkR03exRSYJmPGdfs/export?format=tsv&id=14AdaJ6cmU0kvQ4ulq9pWpjdZL5tkR03exRSYJmPGdfs&gid=0' | grep -v "New format" \
  | sed -e 's,[[:space:]]*$,,' > licenses_changes.ntxt
curl -fsSL -o licenses.json https://raw.githubusercontent.com/spdx/license-list-data/master/json/licenses.json
# fetch everything before replacing any file, so a failed curl cannot leave the tree half-updated
curl -fsSL -o licenses_exceptions.txt https://raw.githubusercontent.com/openSUSE/obs-service-format_spec_file/master/licenses_exceptions.txt
SPDX_LIST_VERSION=$(jq -r '.licenseListVersion' licenses.json)
SPDX_FETCH_DATE=$(date -u +%F)

: > licenses_changes.ptxt
grep ^SUSE- licenses_changes.ntxt | cut -d'	' -f1 | while read -r l; do
  echo "$l	$l" >> licenses_changes.ptxt ;
  # add + only to non or-later ones, otheriwse add the +
  if [[ ${l/-or-later/} == ${l} ]]; then
    echo "$l+	$l+" >> licenses_changes.ptxt ;
  else
    echo "$l	${l/-or-later/}+" >> licenses_changes.ptxt ;
  fi
done

for i in $(jq -r '.licenses | .[] | select(.isDeprecatedLicenseId|not) | .licenseId' licenses.json); do
  echo "$i	$i" >> licenses_changes.ntxt ;
  echo "$i+	$i+" >> licenses_changes.ntxt ;
  # For these that can be "or later" generate also replacement of + SPDX-2.0
  if [[ ${i/-or-later/} != ${i} ]]; then
    echo "$i	${i/-or-later/}+" >> licenses_changes.ntxt ;
  fi
  # replace old -only without the name
  if [[ ${i/-only/} != ${i} ]]; then
    echo "$i	${i/-only/}" >> licenses_changes.ntxt ;
  fi
done
IFS=:
dups=$(tr '	' ':' < licenses_changes.ntxt | while read -r nl ol; do echo "$nl"; done | sed -e 's,^,B-,; s,B-SUSE-,A-,' | sort | uniq | sed -e 's,^.-,,' | sort | uniq -d)
if test -n "$dups"; then 
  echo "SUSE DUPS $dups"
  exit 1
fi

: > licenses_changes.raw
(
echo "<!-- Generated by license-update.sh from SPDX license list ${SPDX_LIST_VERSION} (fetched ${SPDX_FETCH_DATE}) and the SUSE additions; do not edit by hand. -->"
echo ""
echo "# [SPDX Licenses](http://spdx.org/licenses)"
echo ""
echo "License Tag | Description"
echo "----------- | -----------"
IFS=:
jq -r '.licenses | .[] | select(.isDeprecatedLicenseId|not) | [.licenseId, ":", .name] | add' licenses.json | sort | while read license text; do
  echo "$license | $text"
  echo "$license" >> licenses_changes.raw
done
unset IFS

echo ""
echo "# SUSE Additions"
echo ""
echo "|License Tag|"
echo "|-----------|"

IFS=:
grep -E "^(LicenseRef-SUSE-|SUSE-)" licenses_changes.ntxt | cut -d'	' -f1 | sort -u | while read nl; do
  echo "|$nl|"
done
unset IFS

rm licenses_changes.raw
) > SPDX-LICENSES.md.tmp

# the provenance header is prepended after the sort, so it stays first
# whatever the locale collates '#' as
cat licenses_changes.ntxt licenses_changes.ptxt | sort -u > spec_cleaner/data/licenses_changes.txt.tmp
{
  echo "# SPDX license list ${SPDX_LIST_VERSION}, fetched ${SPDX_FETCH_DATE}"
  cat spec_cleaner/data/licenses_changes.txt.tmp
} > spec_cleaner/data/licenses_changes.txt
rm spec_cleaner/data/licenses_changes.txt.tmp
mv SPDX-LICENSES.md.tmp SPDX-LICENSES.md
rm licenses_changes.ntxt licenses_changes.ptxt licenses.json

# License exceptions are a curated list maintained alongside the conversions
# in obs-service-format_spec_file; rpmcrab consumes them as ValidLicenseExceptions.
{
  echo "# Sourced from openSUSE/obs-service-format_spec_file licenses_exceptions.txt, fetched ${SPDX_FETCH_DATE}"
  echo "# URL: https://github.com/openSUSE/obs-service-format_spec_file/blob/master/licenses_exceptions.txt"
  cat licenses_exceptions.txt
} > spec_cleaner/data/license_exceptions.txt
rm licenses_exceptions.txt

