#!/bin/sh
# vim: set ts=4 sw=4 et: coding=UTF-8

#
# Copyright (c) 2009, Novell, Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#  * Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#  * Neither the name of the <ORGANIZATION> nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
#
# (Licensed under the simplified BSD license)
#
# Authors:
#   Vincent Untz <vuntz@novell.com>
#   Pavol Rusnak <prusnak@opensuse.org>
#

sed -i '
# use /^%files/ instead of 1 below when you want to replace macros only in %files section
# otherwise all macros are replaced until line with %changelog is hit

1,/^%changelog/ {

# replace prefix /usr

s:%_prefix:%{_prefix}:g
s:/usr:%{_prefix}:g
s:%prefix:%{_prefix}:g
s:%{prefix}:%{_prefix}:g

# replace bindir /usr/bin

s:%_bindir:%{_bindir}:g
s:%{_prefix}/bin:%{_bindir}:g

# replace sbindir /usr/sbin

s:%_sbindir:%{_sbindir}:g
s:%{_prefix}/sbin:%{_sbindir}:g

# replace includedir /usr/include

s:%_includedir:%{_includedir}:g
s:%{_prefix}/include:%{_includedir}:g

# replace datadir /usr/share

s:%_datadir:%{_datadir}:g
s:%{_prefix}/share:%{_datadir}:g

# replace mandir /usr/share/man

s:%_mandir:%{_mandir}:g
s:%{_datadir}/man:%{_mandir}:g

# replace infodir /usr/share/info

s:%_infodir:%{_infodir}:g
s:%{_datadir}/info:%{_infodir}:g

# replace lib

s:%_lib:%{_lib}:g

# replace libdir (unfortunately cannot replace /usr/lib{,64} directly - could be libexecdir)

s:%_libdir:%{_libdir}:g
s:%{_prefix}/%{_lib}:%{_libdir}:g

# replace libexecdir

s:%_libexecdir:%{_libexecdir}:g

# replace sysconfdir /etc

s:%_sysconfdir:%{_sysconfdir}:g
s:/etc:%{_sysconfdir}:g

# replace localstatedir /var

s:%_localstatedir:%{_localstatedir}:g
s:/var:%{_localstatedir}:g

# replace buildroot

s:${RPM_BUILD_ROOT}:%{buildroot}:g
s:$RPM_BUILD_ROOT:%{buildroot}:g
s:%buildroot:%{buildroot}:g

# replace optflags

s:${RPM_OPT_FLAGS}:%{optflags}:g
s:$RPM_OPT_FLAGS:%{optflags}:g
s:%optflags:%{optflags}:g

}
' *.spec
