BuildRequires: cairo-devel
BuildRequires: dbus-1-devel
BuildRequires: dbus-1-glib-devel
BuildRequires: gconf2-devel
BuildRequires: exo-devel
BuildRequires: glib2-devel
BuildRequires: gtk2-devel
BuildRequires: hal-devel
BuildRequires: libexif-devel
BuildRequires: libgarcon-devel
BuildRequires: libglade2-devel
BuildRequires: libgladeui-1_0-devel
BuildRequires: libgudev-1_0-devel
BuildRequires: libnotify-devel
BuildRequires: libwnck-devel
BuildRequires: libxfce4ui-devel
BuildRequires: libxfce4util-devel
BuildRequires: libxfcegui4-devel
BuildRequires: libxfconf-devel
BuildRequires: libxklavier-devel
BuildRequires: libxml2-devel
BuildRequires: startup-notification-devel
BuildRequires: xfce4-panel-devel

Requires: cairo-devel
Requires: dbus-1-devel
Requires: dbus-1-glib-devel
Requires: gconf2-devel
Requires: exo-devel
Requires: glib2-devel
Requires: gtk2-devel
Requires: hal-devel
Requires: libexif-devel
Requires: libgarcon-devel
Requires: libglade2-devel
Requires: libgladeui-1_0-devel
Requires: libgudev-1_0-devel
Requires: libnotify-devel
Requires: libwnck-devel
Requires: libxfce4ui-devel
Requires: libxfce4util-devel
Requires: libxfcegui4-devel
Requires: libxfconf-devel
Requires: libxklavier-devel
Requires: libxml2-devel
Requires: startup-notification-devel
Requires: xfce4-panel-devel
