BuildRequires: pkgconfig(bla)
BuildRequires: ruby(something)
BuildRequires: rocket-devel
BuildRequires: perl(DBI)
BuildRequires: perl-devel
BuildRequires: cmake(dla)
BuildRequires: something-devel
BuildRequires: cmake(bla)
BuildRequires: cbla-devel
