Name:           bundle-lang-other
BuildArch:      noarch
Provides:       locale(aa;af;am;ang;as;az;be;bg;bn;bo;br;bs;byn)
Provides:       locale(csb;cy;dv;dz;ee;eo;et;eu)
Provides:       locale(fa;fo;fy;ga;gd;gez;gl;gn;gu;gv;haw;he;hi;hr)
Provides:       locale(hy;ia;id;is;iu;ka;kk;kl;km)
Provides:       locale(kn;kok;ku;kw;ky;lg;li;lo;lt;lv;mg;mi;mk;ml;mn;mr;ms;mt;my;nds;ne)
Provides:       locale(nn;nso;oc;om;or;pa;ps;rm;ro)
Provides:       locale(rw;sa;se;si;sid;sk;sl;so;sp;sq;sr)
Provides:       locale(ss;st;sw;syr;ta;te;tg;th;ti;tig;tk;tl;tr;tt;ug;uk;ur;urd;uz)
Provides:       locale(ve;ven;vi;wa;wal;wo;xh;yi;yo;zu)
Source0:        README.other
