#
# Please submit bugfixes or comments via http://bugs.opensuse.org/
#

BuildRequires:  pkgconfig(cairo)
BuildRequires:  pkgconfig(dbus-1)
BuildRequires:  pkgconfig(dbus-glib-1)
BuildRequires:  pkgconfig(exo-1)
BuildRequires:  pkgconfig(garcon-1)
BuildRequires:  pkgconfig(gconf-2.0)
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  pkgconfig(gtk-2.0)
BuildRequires:  pkgconfig(gudev-1.0)
BuildRequires:  pkgconfig(hal)
BuildRequires:  pkgconfig(libexif)
BuildRequires:  pkgconfig(libglade-2.0)
BuildRequires:  pkgconfig(libgladeui-1.0)
BuildRequires:  pkgconfig(libnotify)
BuildRequires:  pkgconfig(libstartup-notification-1.0)
BuildRequires:  pkgconfig(libwnck-1.0)
BuildRequires:  pkgconfig(libxfce4panel-1.0)
BuildRequires:  pkgconfig(libxfce4ui-1)
BuildRequires:  pkgconfig(libxfce4util-1.0)
BuildRequires:  pkgconfig(libxfcegui4-1.0)
BuildRequires:  pkgconfig(libxfconf-0)
BuildRequires:  pkgconfig(libxklavier)
BuildRequires:  pkgconfig(libxml-2.0)

Requires:       pkgconfig(cairo)
Requires:       pkgconfig(dbus-1)
Requires:       pkgconfig(dbus-glib-1)
Requires:       pkgconfig(exo-1)
Requires:       pkgconfig(garcon-1)
Requires:       pkgconfig(gconf-2.0)
Requires:       pkgconfig(glib-2.0)
Requires:       pkgconfig(gtk-2.0)
Requires:       pkgconfig(gudev-1.0)
Requires:       pkgconfig(hal)
Requires:       pkgconfig(libexif)
Requires:       pkgconfig(libglade-2.0)
Requires:       pkgconfig(libgladeui-1.0)
Requires:       pkgconfig(libnotify)
Requires:       pkgconfig(libstartup-notification-1.0)
Requires:       pkgconfig(libwnck-1.0)
Requires:       pkgconfig(libxfce4panel-1.0)
Requires:       pkgconfig(libxfce4ui-1)
Requires:       pkgconfig(libxfce4util-1.0)
Requires:       pkgconfig(libxfcegui4-1.0)
Requires:       pkgconfig(libxfconf-0)
Requires:       pkgconfig(libxklavier)
Requires:       pkgconfig(libxml-2.0)
